name: Build Minecraft Mod
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Using 8.8 because it is the most stable with Loom 1.7-1.8
      - name: Setup Gradle 8.8
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.8'

      - name: Build Mod
        run: chmod +x gradlew && ./gradlew build --no-daemon

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RaiderMod-1.21.1-Build
          path: build/libs/*.jar
          
